// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfpYjo3zN3vfr1NwmtKCwaRrwoKaIe0LU',
    appId: '1:845056101890:web:f3a7b8ed9fcfcb8a00611b',
    messagingSenderId: '845056101890',
    projectId: 'scissorsnewproject',
    authDomain: 'scissorsnewproject.firebaseapp.com',
    storageBucket: 'scissorsnewproject.appspot.com',
    measurementId: 'G-0WYXSCG61E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuU5hUi1YGG_ev8MSj2Ll3l1f8orBtx4Y',
    appId: '1:845056101890:android:efa4a941ccd5609200611b',
    messagingSenderId: '845056101890',
    projectId: 'scissorsnewproject',
    storageBucket: 'scissorsnewproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoarFsyy4eQtZx_YkLKOnMPNHeY4GnkM0',
    appId: '1:845056101890:ios:04de49aa19e4914c00611b',
    messagingSenderId: '845056101890',
    projectId: 'scissorsnewproject',
    storageBucket: 'scissorsnewproject.appspot.com',
    iosBundleId: 'com.example.scissorsnewproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoarFsyy4eQtZx_YkLKOnMPNHeY4GnkM0',
    appId: '1:845056101890:ios:29e7d0bd983f926800611b',
    messagingSenderId: '845056101890',
    projectId: 'scissorsnewproject',
    storageBucket: 'scissorsnewproject.appspot.com',
    iosBundleId: 'com.example.scissorsnewproject.RunnerTests',
  );
}
